#!/bin/bash

# Run this code from the directory the file is. We
# call this directory WORKSPACE. The script required
# the variables HADOOP_HOME and MAHOUT_HOME
#
# This script is thought to run on top of Hadoop in
# *standalone* mode
#
# 1. Inside WORKSPACE create 'lib' directory and
# copy 'mahout_feature.jar' there
#
# 2. Inside WORKSPACE create 'data' directory and
# download the following dataset
#   http://penglab.janelia.org/proj/mRMR/test_nci9_s3.csv
#
# 3. Note: running the script the "output" and "temp"
# directories will be removed

# START configuration

WORKSPACE_DIR='pwd'

OUTPUT_DIR="output"
LIB_DIR="${WORKSPACE_DIR}/lib"
DATA_DIR="data"

FEATURE_SELECTED=5

DATASET=part-r-00000

# END configuration

hadoop dfs  -rmr ${OUTPUT_DIR}/${DATA_DIR}
hadoop dfs  -rmr temp/

# Conversion from CSV to Vectorized data
${MAHOUT_HOME}/bin/mahout hadoop jar ${LIB_DIR}/mahout_feature.jar \
        org.apache.mahout.feature.common.csv.CsvToVectorDriver -libjars /usr/local/mahout/mahout-core-0.7-job.jar\
        -i ${DATA_DIR}/${DATASET} -o ${OUTPUT_DIR}/csv -nc 45

${MAHOUT_HOME}/bin/mahout rowid -i ${OUTPUT_DIR}/csv/part-m-00000 -o ${OUTPUT_DIR}/matrix
#${MAHOUT_HOME}/bin/mahout transpose -i output/matrix/matrix --numRows 60 --numCols 9713

${MAHOUT_HOME}/bin/mahout hadoop jar ${LIB_DIR}/mahout_feature.jar \
	org.apache.mahout.feature.mrmr.MRMRDriver -libjars /usr/local/mahout/mahout-core-0.7-job.jar\
        -i ${OUTPUT_DIR}/matrix/matrix/part-00000 -o ${OUTPUT_DIR}/mrmr -t 348 -nc 1038 -nr 45 -nf ${FEATURE_SELECTED}
